### ISSUE TITLE
DNSproxy open wrt ?

### ISSUE THREAD

**Issue by PerkelSimon** [muink/luci-app-dnsproxy#1]
Hi

is it possible to update the package on open wrt?
the dnsproxy is now @version 0.65-0-1  and the one from open wrt is still on 0.50, thanks

**Comment by muink** [comment]
In fact, the mainline is already [v0.64.1](https://github.com/openwrt/packages/commit/f6714eb01e60d56113b67831bfcd9fc83ea07ef7), but it has not been updated to other branch.

**Comment by PerkelSimon** [comment]
> In fact, the mainline is already [v0.64.1](https://github.com/openwrt/packages/commit/f6714eb01e60d56113b67831bfcd9fc83ea07ef7), but it has not been updated to other branch.

ok great, is it possible to update to the last one, v0.65 ?
thanks a lot, I would like to be able to do on my side for my custom build but not sure how.

**Comment by muink** [comment]
https://downloads.openwrt.org/releases/<VERSION>/packages/<ARCH>/packages/dnsproxy_*.ipk
Manual installation is possible

**Comment by PerkelSimon** [comment]
> https://downloads.openwrt.org/releases//packages//packages/dnsproxy_*.ipk Manual installation is possible

yes this one is 0.64, I hope to see 0.65 soon, just asking, thank you for your time
